sudo: required
language: ruby
cache: bundler
dist: trusty
addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export TZ=America/New_York
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database test_sparc_request;'
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake assets:precompile
jobs:
  include:
    - script:
      - bundle exec rspec spec/api
      - bundle exec rspec spec/extensions
      - bundle exec rspec spec/jobs
      - bundle exec rspec spec/helpers
      - bundle exec rspec spec/mailers
      - bundle exec rspec spec/lib
      - bundle exec rspec spec/models
      - bundle exec rspec spec/views
      - bundle exec rspec spec/controllers
    - script:
      - bundle exec rspec spec/features/dashboard
    - script:
      - bundle exec rspec spec/features/catalog_manager spec/features/surveyor
    - script:
      - bundle exec rspec spec/features/proper
