sudo: false
language: ruby
cache: bundler
dist: trusty
env:
  DISPLAY: :99.0
  RAILS_ENV: test
  CHROME_DRIVER_VERSION: '2.40'

addons:
  chrome: stable

before_install:
  - export TZ=America/New_York
before_script:
  - wget "http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
  - bundle install
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.yml.example config/database.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - mysql -e 'create database test_sparc_request;'
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
jobs:
  include:
    - script:
      - bundle exec rspec spec/api
      - bundle exec rspec spec/extensions
      - bundle exec rspec spec/jobs
      - bundle exec rspec spec/helpers
      - bundle exec rspec spec/mailers
      - bundle exec rspec spec/lib
      - bundle exec rspec spec/models
      - bundle exec rspec spec/views
      - bundle exec rspec spec/controllers
    - script:
      - bundle exec rspec spec/features
